

services:
  web:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./app:/usr/src/app
      - model_volume:/usr/src/app/model
      
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:  # Ensures the database service is healthy before starting dependent services
      test: ["CMD-SHELL", "pg_isready -U user -d milestone_3"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  pgdata:
  model_volume:



      