version: "3.3"

services:
 web:
  build: 
   context: .
   dockerfile: Dockerfile
  expose:
   - "5000"
  volumes:
   - ./src:/src
  command: >
   bash -c "python /src/train.py && flask run --host=0.0.0.0 --port=5000"
  depends_on:
   - db

 nginx:
  build:
   context: .
   dockerfile: Dockerfile.nginx
  ports:
   - "8080:80"
  depends_on:
   - web

 db:
  image: postgres:13
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: postgres
   POSTGRES_HOST_AUTH_METHOD: trust
  healthcheck:
   test: "pg_isready -U postgres"
   interval: 10s
   timeout: 5s
   retries: 5

volumes:
 postgres_data:
