name: DSTA1_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - astunparse=1.6.3
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - expat=2.6.3
  - flatbuffers=24.3.25
  - gast=0.5.3
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - h5py=3.11.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras=3.4.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libcurl=8.9.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - ml_dtypes=0.4.0
  - namex=0.0.7
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - opt_einsum=3.3.0
  - optree=0.12.1
  - packaging=24.1
  - pip=24.2
  - protobuf=4.25.3
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.4
  - python-flatbuffers=24.3.25
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.7.1
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=2.1.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - werkzeug=3.0.3
  - wheel=0.44.0
  - wrapt=1.14.1
  - xz=5.4.6
  - zlib=1.2.13

