version: "3.3"

services:
 web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - ./src/app/model:/app/model
  depends_on:
   - db

 db:
  image: postgres:13
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: postgres
   POSTGRES_HOST_AUTH_METHOD: trust
  healthcheck:
   test: "pg_isready -U postgres"
   interval: 10s
   timeout: 5s
   retries: 5

volumes:
 postgres_data:
